//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BimSpeedStructureBeamDesign.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BimSpeedStructureBeamDesign.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Line Family:.
        /// </summary>
        public static string AUTOBEAM_BREAKLINE {
            get {
                return ResourceManager.GetString("AUTOBEAM_BREAKLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimmension Style:.
        /// </summary>
        public static string AUTOBEAM_DIMSTYLE {
            get {
                return ResourceManager.GetString("AUTOBEAM_DIMSTYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance 2 Dim:.
        /// </summary>
        public static string AUTOBEAM_DISTANCE2DIM {
            get {
                return ResourceManager.GetString("AUTOBEAM_DISTANCE2DIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance 2 dim (Scale 1:1).
        /// </summary>
        public static string AUTOBEAM_DISTANCE2DIMSCALE {
            get {
                return ResourceManager.GetString("AUTOBEAM_DISTANCE2DIMSCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance BreakLine-&gt;Beam:.
        /// </summary>
        public static string AUTOBEAM_DISTANCEBREAKLINE_BEAM {
            get {
                return ResourceManager.GetString("AUTOBEAM_DISTANCEBREAKLINE-BEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Dim-&gt;Beam:.
        /// </summary>
        public static string AUTOBEAM_DISTANCEDIMBEAM {
            get {
                return ResourceManager.GetString("AUTOBEAM_DISTANCEDIMBEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Edge-&gt;Beam:.
        /// </summary>
        public static string AUTOBEAM_DISTANCEEAGE_BEAM {
            get {
                return ResourceManager.GetString("AUTOBEAM_DISTANCEEAGE-BEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Tag-&gt;Beam:.
        /// </summary>
        public static string AUTOBEAM_DISTANCETAGBEAM {
            get {
                return ResourceManager.GetString("AUTOBEAM_DISTANCETAGBEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Tag Head-&gt;Beam.
        /// </summary>
        public static string AUTOBEAM_DISTANCETAGHEAD_BEAM {
            get {
                return ResourceManager.GetString("AUTOBEAM_DISTANCETAGHEAD-BEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Tag Y(1:1):.
        /// </summary>
        public static string AUTOBEAM_DISTANCETAGY {
            get {
                return ResourceManager.GetString("AUTOBEAM_DISTANCETAGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting List.
        /// </summary>
        public static string AUTOBEAM_SETTINGLIST {
            get {
                return ResourceManager.GetString("AUTOBEAM_SETTINGLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Name.
        /// </summary>
        public static string AUTOBEAM_SETTINGNAME {
            get {
                return ResourceManager.GetString("AUTOBEAM-SETTINGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string AUTOBEAM_SHEETNAME {
            get {
                return ResourceManager.GetString("AUTOBEAM_SHEETNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Number.
        /// </summary>
        public static string AUTOBEAM_SHEETNUMBER {
            get {
                return ResourceManager.GetString("AUTOBEAM_SHEETNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot Elevation:.
        /// </summary>
        public static string AUTOBEAM_SPOTELEVATION {
            get {
                return ResourceManager.GetString("AUTOBEAM_SPOTELEVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Group Bar Left:.
        /// </summary>
        public static string AUTOBEAM_TAGGROUPBARLEFT {
            get {
                return ResourceManager.GetString("AUTOBEAM_TAGGROUPBARLEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Group Bar Right:.
        /// </summary>
        public static string AUTOBEAM_TAGGROUPBARRIGHT {
            get {
                return ResourceManager.GetString("AUTOBEAM_TAGGROUPBARRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Single Bar Left.
        /// </summary>
        public static string AUTOBEAM_TAGSINGLEBARLEFT {
            get {
                return ResourceManager.GetString("AUTOBEAM_TAGSINGLEBARLEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Single Bar Right:.
        /// </summary>
        public static string AUTOBEAM_TAGSINGLEBARRIGHT {
            get {
                return ResourceManager.GetString("AUTOBEAM_TAGSINGLEBARRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Left Stirrup:.
        /// </summary>
        public static string AUTOBEAM_TAGSTIRRUPLEFT {
            get {
                return ResourceManager.GetString("AUTOBEAM_TAGSTIRRUPLEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Right Stirrup:.
        /// </summary>
        public static string AUTOBEAM_TAGSTIRRUPRIGHT {
            get {
                return ResourceManager.GetString("AUTOBEAM_TAGSTIRRUPRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Block.
        /// </summary>
        public static string AUTOBEAM_TITLEBLOCK {
            get {
                return ResourceManager.GetString("AUTOBEAM_TITLEBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Template:.
        /// </summary>
        public static string AUTOBEAM_VIEWTEMPLATE {
            get {
                return ResourceManager.GetString("AUTOBEAM_VIEWTEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Of Each Cross Section.
        /// </summary>
        public static string BEAM_BEAMSECTION_POSITIONCROSSSECTION {
            get {
                return ResourceManager.GetString("BEAM_BEAMSECTION_POSITIONCROSSSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] beamdrawingsetting {
            get {
                object obj = ResourceManager.GetObject("beamdrawingsetting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Beam.
        /// </summary>
        public static string BEAMREBAR_ALLBEAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_ALLBEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing.
        /// </summary>
        public static string BEAMREBAR_BANVE {
            get {
                return ResourceManager.GetString("BEAMREBAR_BANVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 1:.
        /// </summary>
        public static string BEAMREBAR_BANVE_MATCAT1 {
            get {
                return ResourceManager.GetString("BEAMREBAR_BANVE_MATCAT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 2:.
        /// </summary>
        public static string BEAMREBAR_BANVE_MATCAT2 {
            get {
                return ResourceManager.GetString("BEAMREBAR_BANVE_MATCAT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 3:.
        /// </summary>
        public static string BEAMREBAR_BANVE_MATCAT3 {
            get {
                return ResourceManager.GetString("BEAMREBAR_BANVE_MATCAT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Allows Cutting Rebar.
        /// </summary>
        public static string BEAMREBAR_BANVE_VITRICHOPHEPCATTHEP {
            get {
                return ResourceManager.GetString("BEAMREBAR_BANVE_VITRICHOPHEPCATTHEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Drawing.
        /// </summary>
        public static string BEAMREBAR_BAVEDAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_BAVEDAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam.
        /// </summary>
        public static string BEAMREBAR_BEAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_BEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 3 Sections If Segment Length &gt;.
        /// </summary>
        public static string BEAMREBAR_BEAMSECTION_LENGTHSECTION {
            get {
                return ResourceManager.GetString("BEAMREBAR_BEAMSECTION_LENGTHSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Shop.
        /// </summary>
        public static string BEAMREBAR_BEAMSHOP {
            get {
                return ResourceManager.GetString("BEAMREBAR_BEAMSHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Position in Span.
        /// </summary>
        public static string BEAMREBAR_BEAMSHOP_VITRICATTAINHIPDAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_BEAMSHOP_VITRICATTAINHIPDAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Support.
        /// </summary>
        public static string BEAMREBAR_BEAMSUPPORT {
            get {
                return ResourceManager.GetString("BEAMREBAR_BEAMSUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Bar.
        /// </summary>
        public static string BEAMREBAR_BOTBAR {
            get {
                return ResourceManager.GetString("BEAMREBAR_BOTBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Layer.
        /// </summary>
        public static string BEAMREBAR_BOTLAYER {
            get {
                return ResourceManager.GetString("BEAMREBAR_BOTLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrup Arrangement:.
        /// </summary>
        public static string BEAMREBAR_BOTRI {
            get {
                return ResourceManager.GetString("BEAMREBAR_BOTRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrup Distribution Type :.
        /// </summary>
        public static string BEAMREBAR_BOTRIDAI {
            get {
                return ResourceManager.GetString("BEAMREBAR_BOTRIDAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Setting.
        /// </summary>
        public static string BEAMREBAR_CAUTAO {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Length.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_CDTOITHIEUDOANMOC {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_CDTOITHIEUDOANMOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Go In Column(mm).
        /// </summary>
        public static string BEAMREBAR_CAUTAO_CHIEUDAIANVAOCOT {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_CHIEUDAIANVAOCOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap Length(mm).
        /// </summary>
        public static string BEAMREBAR_CAUTAO_CHIEUDAINOI {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_CHIEUDAINOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Spacer.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_CINKETHEP {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_CINKETHEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Spacer.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_CONKETHEP {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_CONKETHEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Stirrup.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_COTDAIMOC {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_COTDAIMOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Stirrup.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_COTTHEPBOSUNG {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_COTTHEPBOSUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrup for secondary Beam.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_DAIGIACUONGDAMPHU {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_DAIGIACUONGDAMPHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension on both sides.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_DOANKEODAI2BEN {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_DOANKEODAI2BEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanger bar diameter.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_DUONGKINHTHEPVAIBO {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_DUONGKINHTHEPVAIBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Height.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_HEGHTMAX {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_HEGHTMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Height.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_HEIGHTDAMBOTRI {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_HEIGHTDAMBOTRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Height.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_HEIGHTMAX {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_HEIGHTMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing of Add. Stirrup:.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_KCDAIGIACUONG {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_KCDAIGIACUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Type.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_LAYOUTTYPE {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_LAYOUTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Stirrup:.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_SOLUONGDAIGIACUONG {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_SOLUONGDAIGIACUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of hanger bar:.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_SOLUONGTHEPVAIBO {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_SOLUONGTHEPVAIBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer 2:.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_THEPGIOLOP2 {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_THEPGIOLOP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Among The Beam.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_THEPGIUADAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_THEPGIUADAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer 1:.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_THEPGOILOP1 {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_THEPGOILOP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer 3:.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_THEPGOILOP3 {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_THEPGOILOP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar At Support Cut Point :.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_THEPNHIP {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_THEPNHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanger bar of secondary Beam.
        /// </summary>
        public static string BEAMREBAR_CAUTAO_THEPVAIBODAMPHU {
            get {
                return ResourceManager.GetString("BEAMREBAR_CAUTAO_THEPVAIBODAMPHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string BEAMREBAR_COVER {
            get {
                return ResourceManager.GetString("BEAMREBAR_COVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far Clip Offset:.
        /// </summary>
        public static string BEAMREBAR_CREATEBEAMSECTION_FARCLIPOFFSET {
            get {
                return ResourceManager.GetString("BEAMREBAR_CREATEBEAMSECTION_FARCLIPOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide At Scales Coaser Than.
        /// </summary>
        public static string BEAMREBAR_CREATEBEAMSECTION_HIDESCALESCOARSER {
            get {
                return ResourceManager.GetString("BEAMREBAR_CREATEBEAMSECTION_HIDESCALESCOARSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclined Beam.
        /// </summary>
        public static string BEAMREBAR_CREATEBEAMSECTION_INCLINEDBEAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_CREATEBEAMSECTION_INCLINEDBEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Naming.
        /// </summary>
        public static string BEAMREBAR_CREATEBEAMSECTION_PREVIEWNAMING {
            get {
                return ResourceManager.GetString("BEAMREBAR_CREATEBEAMSECTION_PREVIEWNAMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Along Beam.
        /// </summary>
        public static string BEAMREBAR_CREATEBEAMSECTION_SECALONGBEAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_CREATEBEAMSECTION_SECALONGBEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Offset from Side Face.
        /// </summary>
        public static string BEAMREBAR_CREATEBEAMSECTION_SECTIONOFFSETSIDEFACE {
            get {
                return ResourceManager.GetString("BEAMREBAR_CREATEBEAMSECTION_SECTIONOFFSETSIDEFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Now.
        /// </summary>
        public static string BEAMREBAR_CREATEMOW {
            get {
                return ResourceManager.GetString("BEAMREBAR_CREATEMOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Section.
        /// </summary>
        public static string BEAMREBAR_CROSSSECTION {
            get {
                return ResourceManager.GetString("BEAMREBAR_CROSSSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Diameter:.
        /// </summary>
        public static string BEAMREBAR_DKDAICHINH {
            get {
                return ResourceManager.GetString("BEAMREBAR_DKDAICHINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrup Diameter:.
        /// </summary>
        public static string BEAMREBAR_DKDAIMOC {
            get {
                return ResourceManager.GetString("BEAMREBAR_DKDAIMOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Setting .
        /// </summary>
        public static string BEAMREBAR_DRAWINGSETTING {
            get {
                return ResourceManager.GetString("BEAMREBAR_DRAWINGSETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrup Diameter:.
        /// </summary>
        public static string BEAMREBAR_DUONGKINHDAI {
            get {
                return ResourceManager.GetString("BEAMREBAR_DUONGKINHDAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End 1 Length:.
        /// </summary>
        public static string BEAMREBAR_END1LENGTH {
            get {
                return ResourceManager.GetString("BEAMREBAR_END1LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End 2 Length:.
        /// </summary>
        public static string BEAMREBAR_END2LENGTH {
            get {
                return ResourceManager.GetString("BEAMREBAR_END2LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far Clip Offset :.
        /// </summary>
        public static string BEAMREBAR_FARCLIPOFFSET {
            get {
                return ResourceManager.GetString("BEAMREBAR_FARCLIPOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Beam.
        /// </summary>
        public static string BEAMREBAR_HORIZONTAL {
            get {
                return ResourceManager.GetString("BEAMREBAR_HORIZONTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrup Spacing(mm).
        /// </summary>
        public static string BEAMREBAR_KCDAI {
            get {
                return ResourceManager.GetString("BEAMREBAR_KCDAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing A1:.
        /// </summary>
        public static string BEAMREBAR_KCDAIA1 {
            get {
                return ResourceManager.GetString("BEAMREBAR_KCDAIA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing A2:.
        /// </summary>
        public static string BEAMREBAR_KCDAIA2 {
            get {
                return ResourceManager.GetString("BEAMREBAR_KCDAIA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer 1.
        /// </summary>
        public static string BEAMREBAR_LOP1 {
            get {
                return ResourceManager.GetString("BEAMREBAR_LOP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer 2.
        /// </summary>
        public static string BEAMREBAR_LOP2 {
            get {
                return ResourceManager.GetString("BEAMREBAR_LOP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archor L_y Right:.
        /// </summary>
        public static string BEAMREBAR_MAINTOP_BENEOYPHAI {
            get {
                return ResourceManager.GetString("BEAMREBAR_MAINTOP_BENEOYPHAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archor L_y Left:.
        /// </summary>
        public static string BEAMREBAR_MAINTOP_BENEOYTRAI {
            get {
                return ResourceManager.GetString("BEAMREBAR_MAINTOP_BENEOYTRAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archor L_x Left.
        /// </summary>
        public static string BEAMREBAR_MAINTOP_NEOCOTTRAI {
            get {
                return ResourceManager.GetString("BEAMREBAR_MAINTOP_NEOCOTTRAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archor L_x Right:.
        /// </summary>
        public static string BEAMREBAR_MAINTOP_NEOCOTXPHAI {
            get {
                return ResourceManager.GetString("BEAMREBAR_MAINTOP_NEOCOTXPHAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Beams.
        /// </summary>
        public static string BEAMREBAR_MULTIBEAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_MULTIBEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance between 2 anchors.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_KC2LANNEO {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_KC2LANNEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance of 2 layers.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_KHOANGCACH2LOPTHEP {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_KHOANGCACH2LOPTHEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Column.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_NEOCOT {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_NEOCOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Beam.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_NEODAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_NEODAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Foundation.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_NEOMONG {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_NEOMONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor-Stress.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_NEONHANHTHEP {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_NEONHANHTHEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_NEOTHEP {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_NEOTHEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Wall.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_NEOVACH {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_NEOVACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stress Rebar.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_NHANTHEP {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_NHANTHEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor according to :.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_QUIDINHNEO {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_QUIDINHNEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tress Rebar if &amp;lt;.
        /// </summary>
        public static string BEAMREBAR_NHANTHEP_UONTHEP {
            get {
                return ResourceManager.GetString("BEAMREBAR_NHANTHEP_UONTHEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Beam.
        /// </summary>
        public static string BEAMREBAR_OTHER {
            get {
                return ResourceManager.GetString("BEAMREBAR_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick 2 Point Of Beam Segment.
        /// </summary>
        public static string BEAMREBAR_PICK2POINT {
            get {
                return ResourceManager.GetString("BEAMREBAR_PICK2POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string BEAMREBAR_POSITION {
            get {
                return ResourceManager.GetString("BEAMREBAR_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in Section.
        /// </summary>
        public static string BEAMREBAR_POSTIONINSECTION {
            get {
                return ResourceManager.GetString("BEAMREBAR_POSTIONINSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Beam Data.
        /// </summary>
        public static string BEAMREBAR_READBEAMDATA {
            get {
                return ResourceManager.GetString("BEAMREBAR_READBEAMDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar List:.
        /// </summary>
        public static string BEAMREBAR_REBARLIST {
            get {
                return ResourceManager.GetString("BEAMREBAR_REBARLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Beam.
        /// </summary>
        public static string BEAMREBAR_SECONDARY {
            get {
                return ResourceManager.GetString("BEAMREBAR_SECONDARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string BEAMREBAR_SECTION {
            get {
                return ResourceManager.GetString("BEAMREBAR_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Type:.
        /// </summary>
        public static string BEAMREBAR_SECTIONTYPE {
            get {
                return ResourceManager.GetString("BEAMREBAR_SECTIONTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section View Template:.
        /// </summary>
        public static string BEAMREBAR_SECTIONVIEWTEMPLATE {
            get {
                return ResourceManager.GetString("BEAMREBAR_SECTIONVIEWTEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name:.
        /// </summary>
        public static string BEAMREBAR_SHEETNAME {
            get {
                return ResourceManager.GetString("BEAMREBAR_SHEETNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Number:.
        /// </summary>
        public static string BEAMREBAR_SHEETNUMBER {
            get {
                return ResourceManager.GetString("BEAMREBAR_SHEETNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string BEAMREBAR_SOLUONG {
            get {
                return ResourceManager.GetString("BEAMREBAR_SOLUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Span:.
        /// </summary>
        public static string BEAMREBAR_SPAN_BEAMSPAN {
            get {
                return ResourceManager.GetString("BEAMREBAR_SPAN_BEAMSPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Support : .
        /// </summary>
        public static string BEAMREBAR_SPAN_LEFTSUPPORT {
            get {
                return ResourceManager.GetString("BEAMREBAR_SPAN_LEFTSUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Support Width:.
        /// </summary>
        public static string BEAMREBAR_SPAN_LEFTSUPPORTWIDT {
            get {
                return ResourceManager.GetString("BEAMREBAR_SPAN_LEFTSUPPORTWIDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Support:.
        /// </summary>
        public static string BEAMREBAR_SPAN_RIGHTSUPPORT {
            get {
                return ResourceManager.GetString("BEAMREBAR_SPAN_RIGHTSUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Support Width:.
        /// </summary>
        public static string BEAMREBAR_SPAN_RIGHTSUPPORTWIDTH {
            get {
                return ResourceManager.GetString("BEAMREBAR_SPAN_RIGHTSUPPORTWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span Index:.
        /// </summary>
        public static string BEAMREBAR_SPAN_SPANINDEX {
            get {
                return ResourceManager.GetString("BEAMREBAR_SPAN_SPANINDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrup.
        /// </summary>
        public static string BEAMREBAR_STIRRUP {
            get {
                return ResourceManager.GetString("BEAMREBAR_STIRRUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Remaing Span.
        /// </summary>
        public static string BEAMREBAR_STIRRUP_CACNHIP {
            get {
                return ResourceManager.GetString("BEAMREBAR_STIRRUP_CACNHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string BEAMREBAR_STIRRUP_DAILONGKIN {
            get {
                return ResourceManager.GetString("BEAMREBAR_STIRRUP_DAILONGKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.Belt Hook.
        /// </summary>
        public static string BEAMREBAR_STIRRUP_DAIMOC {
            get {
                return ResourceManager.GetString("BEAMREBAR_STIRRUP_DAIMOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hor.Belt Hook.
        /// </summary>
        public static string BEAMREBAR_STIRRUP_DAIMOCNGANG {
            get {
                return ResourceManager.GetString("BEAMREBAR_STIRRUP_DAIMOCNGANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All Span.
        /// </summary>
        public static string BEAMREBAR_STIRRUP_TATCANHIP {
            get {
                return ResourceManager.GetString("BEAMREBAR_STIRRUP_TATCANHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main delete.
        /// </summary>
        public static string BEAMREBAR_STIRRUP_XOADAICHINH {
            get {
                return ResourceManager.GetString("BEAMREBAR_STIRRUP_XOADAICHINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Bar.
        /// </summary>
        public static string BEAMREBAR_THEPCHINH {
            get {
                return ResourceManager.GetString("BEAMREBAR_THEPCHINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Bar.
        /// </summary>
        public static string BEAMREBAR_TOPBAR {
            get {
                return ResourceManager.GetString("BEAMREBAR_TOPBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Layer.
        /// </summary>
        public static string BEAMREBAR_TOPLAYER {
            get {
                return ResourceManager.GetString("BEAMREBAR_TOPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Beam.
        /// </summary>
        public static string BEAMREBAR_VERTICAL {
            get {
                return ResourceManager.GetString("BEAMREBAR_VERTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.Beam.
        /// </summary>
        public static string BEAMREBAR_XBEAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_XBEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.Beam.
        /// </summary>
        public static string BEAMREBAR_YBEAM {
            get {
                return ResourceManager.GetString("BEAMREBAR_YBEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add. Bar Top.
        /// </summary>
        public static string BEAMREBARVIEW2_ADDBARTOP_ADDBARTOP {
            get {
                return ResourceManager.GetString("BEAMREBARVIEW2_ADDBARTOP_ADDBARTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrups Type.
        /// </summary>
        public static string BEAMREBARVIEW2_KIEUTHEPDAI {
            get {
                return ResourceManager.GetString("BEAMREBARVIEW2_KIEUTHEPDAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrups set up.
        /// </summary>
        public static string BEAMREBARVIEW2_THIETLAPTHEPDAI {
            get {
                return ResourceManager.GetString("BEAMREBARVIEW2_THIETLAPTHEPDAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Infor.
        /// </summary>
        public static string BEAMREBARVIEW2_ThongSoCacThanhCotThep {
            get {
                return ResourceManager.GetString("BEAMREBARVIEW2_ThongSoCacThanhCotThep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop View.
        /// </summary>
        public static string BEMAREBAR_CROPVIEW {
            get {
                return ResourceManager.GetString("BEMAREBAR_CROPVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE COLUMN FROM AUTOCAD FILE.
        /// </summary>
        public static string COLUMN_FROM_CAD_VIEW_TITLE {
            get {
                return ResourceManager.GetString("COLUMN_FROM_CAD_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string COMMON_ADD {
            get {
                return ResourceManager.GetString("COMMON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addbot.
        /// </summary>
        public static string COMMON_ADDBOT {
            get {
                return ResourceManager.GetString("COMMON_ADDBOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string COMMON_AREA {
            get {
                return ResourceManager.GetString("COMMON_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string COMMON_BACK {
            get {
                return ResourceManager.GetString("COMMON_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Level :.
        /// </summary>
        public static string COMMON_BASELEVEL {
            get {
                return ResourceManager.GetString("COMMON_BASELEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Offset :.
        /// </summary>
        public static string COMMON_BASEOFFSET {
            get {
                return ResourceManager.GetString("COMMON_BASEOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        public static string COMMON_BOT {
            get {
                return ResourceManager.GetString("COMMON_BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botdiameter.
        /// </summary>
        public static string COMMON_BOTBAR {
            get {
                return ResourceManager.GetString("COMMON_BOTBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bottom bar.
        /// </summary>
        public static string COMMON_BOTBARNUMBER {
            get {
                return ResourceManager.GetString("COMMON_BOTBARNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot hook.
        /// </summary>
        public static string COMMON_BOTTOMHOOK {
            get {
                return ResourceManager.GetString("COMMON_BOTTOMHOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string COMMON_CANCEL {
            get {
                return ResourceManager.GetString("COMMON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string COMMON_CLOSE {
            get {
                return ResourceManager.GetString("COMMON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Cover.
        /// </summary>
        public static string COMMON_COVER {
            get {
                return ResourceManager.GetString("COMMON_COVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string COMMON_CREATE {
            get {
                return ResourceManager.GetString("COMMON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string COMMON_DEFAULT {
            get {
                return ResourceManager.GetString("COMMON_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string COMMON_DELETE {
            get {
                return ResourceManager.GetString("COMMON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string COMMON_DELETEALL {
            get {
                return ResourceManager.GetString("COMMON_DELETEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept :.
        /// </summary>
        public static string COMMON_DEPT {
            get {
                return ResourceManager.GetString("COMMON_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string COMMON_DIAMETER {
            get {
                return ResourceManager.GetString("COMMON_DIAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D Left.
        /// </summary>
        public static string COMMON_DLEFT {
            get {
                return ResourceManager.GetString("COMMON_DLEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D Right.
        /// </summary>
        public static string COMMON_DRIGHT {
            get {
                return ResourceManager.GetString("COMMON_DRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges number.
        /// </summary>
        public static string COMMON_EDGENUMBER {
            get {
                return ResourceManager.GetString("COMMON_EDGENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Point.
        /// </summary>
        public static string COMMON_ENDPOINT {
            get {
                return ResourceManager.GetString("COMMON_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Type.
        /// </summary>
        public static string COMMON_ENDTYPE {
            get {
                return ResourceManager.GetString("COMMON_ENDTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any elements.
        /// </summary>
        public static string COMMON_ERRORMESSAGE {
            get {
                return ResourceManager.GetString("COMMON_ERRORMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string COMMON_EXPORT {
            get {
                return ResourceManager.GetString("COMMON_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family :.
        /// </summary>
        public static string COMMON_FAMILY {
            get {
                return ResourceManager.GetString("COMMON_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor type:.
        /// </summary>
        public static string COMMON_FLOORTYPE {
            get {
                return ResourceManager.GetString("COMMON_FLOORTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid types :.
        /// </summary>
        public static string COMMON_GRIDTYPES {
            get {
                return ResourceManager.GetString("COMMON_GRIDTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string COMMON_GUIDE {
            get {
                return ResourceManager.GetString("COMMON_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string COMMON_HEIGHT {
            get {
                return ResourceManager.GetString("COMMON_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height :.
        /// </summary>
        public static string COMMON_HEIGHTFAMILY {
            get {
                return ResourceManager.GetString("COMMON_HEIGHTFAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsColumn.
        /// </summary>
        public static string COMMON_ISCOLUMN {
            get {
                return ResourceManager.GetString("COMMON_ISCOLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string COMMON_LAYER {
            get {
                return ResourceManager.GetString("COMMON_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Radio.
        /// </summary>
        public static string COMMON_LEFRADIO {
            get {
                return ResourceManager.GetString("COMMON_LEFRADIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string COMMON_LEFT {
            get {
                return ResourceManager.GetString("COMMON_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Length.
        /// </summary>
        public static string COMMON_LEFTLENGTH {
            get {
                return ResourceManager.GetString("COMMON_LEFTLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length .
        /// </summary>
        public static string COMMON_LENGTH {
            get {
                return ResourceManager.GetString("COMMON_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level :.
        /// </summary>
        public static string COMMON_LEVEL {
            get {
                return ResourceManager.GetString("COMMON_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string COMMON_LOAD {
            get {
                return ResourceManager.GetString("COMMON_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string COMMON_MARK {
            get {
                return ResourceManager.GetString("COMMON_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string COMMON_MODIFY {
            get {
                return ResourceManager.GetString("COMMON_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming.
        /// </summary>
        public static string COMMON_NAMING {
            get {
                return ResourceManager.GetString("COMMON_NAMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string COMMON_NEXT {
            get {
                return ResourceManager.GetString("COMMON_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string COMMON_NOTIFY {
            get {
                return ResourceManager.GetString("COMMON_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string COMMON_NUMBER {
            get {
                return ResourceManager.GetString("COMMON_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset from level  : .
        /// </summary>
        public static string COMMON_OFFSETFROMLEVEL {
            get {
                return ResourceManager.GetString("COMMON_OFFSETFROMLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string COMMON_OK {
            get {
                return ResourceManager.GetString("COMMON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string COMMON_OTHER {
            get {
                return ResourceManager.GetString("COMMON_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramater.
        /// </summary>
        public static string COMMON_PARAMATER {
            get {
                return ResourceManager.GetString("COMMON_PARAMATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Point.
        /// </summary>
        public static string COMMON_PICKPOINT {
            get {
                return ResourceManager.GetString("COMMON_PICKPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in Section.
        /// </summary>
        public static string COMMON_POSTIONINSECTION {
            get {
                return ResourceManager.GetString("COMMON_POSTIONINSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string COMMON_PROCESS {
            get {
                return ResourceManager.GetString("COMMON_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius .
        /// </summary>
        public static string COMMON_RADIUS {
            get {
                return ResourceManager.GetString("COMMON_RADIUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Of Operation.
        /// </summary>
        public static string COMMON_RANGEOFOPERATION {
            get {
                return ResourceManager.GetString("COMMON_RANGEOFOPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar diameter.
        /// </summary>
        public static string COMMON_REBAR {
            get {
                return ResourceManager.GetString("COMMON_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string COMMON_REMOVE {
            get {
                return ResourceManager.GetString("COMMON_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string COMMON_RIGHT {
            get {
                return ResourceManager.GetString("COMMON_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Length.
        /// </summary>
        public static string COMMON_RIGHTLENGTH {
            get {
                return ResourceManager.GetString("COMMON_RIGHTLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Radio.
        /// </summary>
        public static string COMMON_RIGHTRADIO {
            get {
                return ResourceManager.GetString("COMMON_RIGHTRADIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string COMMON_SAVE {
            get {
                return ResourceManager.GetString("COMMON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from cad.
        /// </summary>
        public static string COMMON_SELECTFROMCAD {
            get {
                return ResourceManager.GetString("COMMON_SELECTFROMCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string COMMON_SELECTION {
            get {
                return ResourceManager.GetString("COMMON_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string COMMON_SETTING {
            get {
                return ResourceManager.GetString("COMMON_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slab type:.
        /// </summary>
        public static string COMMON_SLABRYPE {
            get {
                return ResourceManager.GetString("COMMON_SLABRYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        public static string COMMON_SPACING {
            get {
                return ResourceManager.GetString("COMMON_SPACING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing rebar.
        /// </summary>
        public static string COMMON_SPACINGREBAR {
            get {
                return ResourceManager.GetString("COMMON_SPACINGREBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing stirrup.
        /// </summary>
        public static string COMMON_SPACINGSTIRRUP {
            get {
                return ResourceManager.GetString("COMMON_SPACINGSTIRRUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string COMMON_START {
            get {
                return ResourceManager.GetString("COMMON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Point.
        /// </summary>
        public static string COMMON_STARTPOINT {
            get {
                return ResourceManager.GetString("COMMON_STARTPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Type.
        /// </summary>
        public static string COMMON_STARTYPE {
            get {
                return ResourceManager.GetString("COMMON_STARTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrup diameter.
        /// </summary>
        public static string COMMON_STIRRUP {
            get {
                return ResourceManager.GetString("COMMON_STIRRUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string COMMON_TEXT {
            get {
                return ResourceManager.GetString("COMMON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness :.
        /// </summary>
        public static string COMMON_THICKNESS {
            get {
                return ResourceManager.GetString("COMMON_THICKNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Section/Image.
        /// </summary>
        public static string COMMON_TOGGLESECTIONIMAGE {
            get {
                return ResourceManager.GetString("COMMON_TOGGLESECTIONIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string COMMON_TOP {
            get {
                return ResourceManager.GetString("COMMON_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topdiameter.
        /// </summary>
        public static string COMMON_TOPBAR {
            get {
                return ResourceManager.GetString("COMMON_TOPBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of top bar.
        /// </summary>
        public static string COMMON_TOPBARNUMBER {
            get {
                return ResourceManager.GetString("COMMON_TOPBARNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top hook.
        /// </summary>
        public static string COMMON_TOPHOOK {
            get {
                return ResourceManager.GetString("COMMON_TOPHOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Level :.
        /// </summary>
        public static string COMMON_TOPLEVEL {
            get {
                return ResourceManager.GetString("COMMON_TOPLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Offset :.
        /// </summary>
        public static string COMMON_TOPOFFSET {
            get {
                return ResourceManager.GetString("COMMON_TOPOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string COMMON_TOTAL {
            get {
                return ResourceManager.GetString("COMMON_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string COMMON_UNDO {
            get {
                return ResourceManager.GetString("COMMON_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string COMMON_UPDATE {
            get {
                return ResourceManager.GetString("COMMON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string COMMON_WIDTH {
            get {
                return ResourceManager.GetString("COMMON_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width : .
        /// </summary>
        public static string COMMON_WITDHFAMILY {
            get {
                return ResourceManager.GetString("COMMON_WITDHFAMILY", resourceCulture);
            }
        }
    }
}
